services:
  - type: web
    name: gci-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: KAFKA_BROKER_URL
        value: "mocked"
      - key: REDIS_URI
        value: "mocked"
      - key: POSTGRES_SERVER
        value: "mocked"
      - key: TIMESCALEDB_SERVER
        value: "mocked"

  - type: web
    name: gci-frontend
    env: static
    rootDir: frontend
    buildCommand: "npm install && npx vite build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: gci-backend
          envVarKey: RENDER_EXTERNAL_URL
